"""Domain model: every Pydantic v2 type that crosses a module boundary.

CLAUDE.md golden rule 6 is "typed everywhere, no untyped dicts crossing module
lines". This package is the vocabulary that makes that possible, and it depends on
nothing else in CostSentinel -- providers, agents, guardrails and reports all depend
inward on it.
"""

from costsentinel.domain.analysis import (
    ContributingFactor,
    FactorKind,
    RankingScore,
    RootCause,
)
from costsentinel.domain.common import (
    Confidence,
    Currency,
    Frozen,
    MoneyAmount,
    Percentage,
    Provenance,
    ProvenanceSource,
    Verification,
    utc_now,
)
from costsentinel.domain.estate import (
    CostPoint,
    CostSeries,
    Environment,
    Estate,
    Reservation,
    Resource,
    ResourceKind,
    ResourceMetrics,
    ResourceState,
    SkuPrice,
    Subscription,
)
from costsentinel.domain.governance import (
    ActionClassification,
    ApprovalDecision,
    ApprovalRequest,
    AuditEvent,
    AuditEventType,
    Decision,
    RouteAction,
    SupervisorDecision,
)
from costsentinel.domain.observability import (
    LLMCallMetrics,
    ModelTier,
    NodeMetrics,
    RoutingDecision,
    RunMetrics,
    TokenPrice,
    TokenUsage,
)
from costsentinel.domain.recommendations import (
    MONTHS_PER_YEAR,
    ActionClass,
    ActionType,
    PricedOption,
    Recommendation,
    SavingsEstimate,
)
from costsentinel.domain.report import (
    ApprovalQueueItem,
    ClientReport,
    ReportFinding,
    ReportPeriod,
    ReportSeverity,
    ReportTotals,
    ScanResult,
    WasteKindSummary,
)
from costsentinel.domain.signals import (
    AnomalyDirection,
    CostAnomaly,
    Observation,
    WasteKind,
    WasteSignal,
)
from costsentinel.domain.state import ScanState

__all__ = [
    "MONTHS_PER_YEAR",
    "ActionClass",
    "ActionClassification",
    "ActionType",
    "AnomalyDirection",
    "ApprovalDecision",
    "ApprovalQueueItem",
    "ApprovalRequest",
    "AuditEvent",
    "AuditEventType",
    "ClientReport",
    "Confidence",
    "ContributingFactor",
    "CostAnomaly",
    "CostPoint",
    "CostSeries",
    "Currency",
    "Decision",
    "Environment",
    "Estate",
    "FactorKind",
    "Frozen",
    "LLMCallMetrics",
    "ModelTier",
    "MoneyAmount",
    "NodeMetrics",
    "Observation",
    "Percentage",
    "PricedOption",
    "Provenance",
    "ProvenanceSource",
    "RankingScore",
    "Recommendation",
    "ReportFinding",
    "ReportPeriod",
    "ReportSeverity",
    "ReportTotals",
    "Reservation",
    "Resource",
    "ResourceKind",
    "ResourceMetrics",
    "ResourceState",
    "RootCause",
    "RouteAction",
    "RoutingDecision",
    "RunMetrics",
    "SavingsEstimate",
    "ScanResult",
    "ScanState",
    "SkuPrice",
    "Subscription",
    "SupervisorDecision",
    "TokenPrice",
    "TokenUsage",
    "Verification",
    "WasteKind",
    "WasteKindSummary",
    "WasteSignal",
    "utc_now",
]
